services:
  web:
    build: .
    container_name: web
    ports:
      - 80:80
    environment:
      - DJANGO_SECRET_KEY="django-insecure-q1w2e3r4t5y6u7i8o9p0"
      - DJANGO_DEBUG_MODE=1
      - DJANGO_LANGUAGE_CODE=en
      - DJANGO_TIMEZONE=UTC
      - SQLITE_DB=db.sqlite3
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:80"
